<?php

declare(strict_types=1);

namespace Vortos\Setup\Service;

final class EnvironmentFileWriter
{
    private const SECTION_BEFORE = [
        'APP_NAME'                => 'App',
        'SERVER_NAME'             => 'HTTP / Runtime',
        'JWT_SECRET'              => 'Security',
        'VORTOS_WRITE_DB_DRIVER'  => 'Write Database',
        'VORTOS_READ_DB_DRIVER'   => 'Read Database',
        'VORTOS_CACHE_DRIVER'     => 'Cache',
        'VORTOS_MESSAGING_DRIVER' => 'Messaging',
    ];

    public function __construct(private readonly string $projectDir) {}

    /** @return array<string, string> */
    public function readKnownValues(): array
    {
        $values = [];
        $path = $this->projectDir . DIRECTORY_SEPARATOR . '.env';

        if (!is_file($path)) {
            return $values;
        }

        foreach (preg_split('/\R/', (string) file_get_contents($path)) ?: [] as $line) {
            if (!preg_match('/^\s*([A-Z0-9_]+)=(.*)$/', $line, $match)) {
                continue;
            }

            $values[$match[1]] = $this->unquote(trim($match[2]));
        }

        return $values;
    }

    /**
     * Write all setup values to the single .env file.
     *
     * @param array<string, string> $values
     * @return array{path: string, written: string[], updated: string[], unchanged: string[], backup: ?string}
     */
    public function write(array $values, bool $dryRun = false, bool $backup = true): array
    {
        return $this->updateFile(
            $this->projectDir . DIRECTORY_SEPARATOR . '.env',
            $values,
            $dryRun,
            $backup,
        );
    }

    /**
     * @param array<string, string> $values
     * @return array{path: string, written: string[], updated: string[], unchanged: string[], backup: ?string}
     */
    private function updateFile(string $path, array $values, bool $dryRun, bool $backup): array
    {
        $existing = is_file($path) ? (string) file_get_contents($path) : '';
        $lines = $existing === '' ? [] : preg_split('/\R/', rtrim($existing, "\r\n"));
        $lines = is_array($lines) ? $lines : [];
        // $newFile = $lines === [];
        $index = [];

        if ($lines === [] && !$dryRun) {
            $lines[] = '# Generated by vortos:setup — do not commit this file.';
            $lines[] = '# Copy .env.example, then run: php vortos setup';
        }

        foreach ($lines as $line => $content) {
            if (preg_match('/^\s*([A-Z0-9_]+)=/', $content, $match)) {
                $index[$match[1]] = $line;
            }
        }

        $written = [];
        $updated = [];
        $unchanged = [];

        foreach ($values as $key => $value) {
            $entry = $key . '=' . $this->quote($value);

            if (isset($index[$key])) {
                if ($lines[$index[$key]] === $entry) {
                    $unchanged[] = $key;
                    continue;
                }

                $lines[$index[$key]] = $entry;
                $updated[] = $key;
                continue;
            }

            // if ($newFile) {
            //     if ($lines === []) {
            //         $lines[] = '# Generated by vortos:setup — do not commit this file.';
            //         $lines[] = '# Copy .env.example, then run: php vortos setup';
            //         $lines[] = '';
            //     }

            //     if (isset(self::SECTION_BEFORE[$key])) {
            //         $lines[] = '';
            //         $lines[] = '# ' . str_repeat('-', 58);
            //         $lines[] = '# ' . self::SECTION_BEFORE[$key];
            //         $lines[] = '# ' . str_repeat('-', 58);
            //     }
            // }

            if (isset(self::SECTION_BEFORE[$key])) {
                $title = self::SECTION_BEFORE[$key];
                if (!str_contains($existing, '# ' . $title)) {
                    $lines[] = '';
                    $lines[] = '# ' . str_repeat('-', 58);
                    $lines[] = '# ' . $title;
                    $lines[] = '# ' . str_repeat('-', 58);
                }
            }

            $lines[] = $entry;
            $written[] = $key;
        }

        $backupPath = null;

        if (!$dryRun && ($written !== [] || $updated !== [])) {
            if (is_file($path) && $backup) {
                $backupPath = $path . '.bak.' . date('YmdHis');
                copy($path, $backupPath);
            }

            file_put_contents($path, implode("\n", $lines) . "\n", LOCK_EX);
        }

        return [
            'path'      => $path,
            'written'   => $written,
            'updated'   => $updated,
            'unchanged' => $unchanged,
            'backup'    => $backupPath,
        ];
    }

    private function quote(string $value): string
    {
        if ($value === '' || preg_match('/[\s#"\']/', $value)) {
            return '"' . str_replace(['\\', '"'], ['\\\\', '\\"'], $value) . '"';
        }

        return $value;
    }

    private function unquote(string $value): string
    {
        if (
            strlen($value) >= 2
            && (($value[0] === '"' && $value[-1] === '"') || ($value[0] === "'" && $value[-1] === "'"))
        ) {
            return substr($value, 1, -1);
        }

        return $value;
    }
}
